### ISSUE TITLE
Error: Not match the saml-schema-protocol-2.0.xsd

### ISSUE THREAD

**Issue by natebird** [lawrencepit/ruby-saml-idp#26]
I'm getting the following error. `Response Invalid. Errors: ["Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd"]`

This is just a simple test between a simple app with the ruby-saml-idp gem installed and the [ruby-saml-example](https://github.com/onelogin/ruby-saml-example) application.

Can anyone point me in the right direction to troubleshoot this?

**Comment by dereke** [comment]
I'm getting this as well..
can you offer any suggestions @lawrencepit ?

**Comment by dereke** [comment]
I found a solution to this. I am using `ruby-saml` gem to parse responses. In the settings for it I set `soft = false` which raised the actual exception telling me what the error was.

My issue was that it did not like the x509 cert. Turned out it just needed to be base64 encoded and then it was fine.
